### ISSUE TITLE
Dexcom bridge not working with EU account

### ISSUE THREAD

**Issue by berpj** [nightscout/cgm-remote-monitor#1818] opened 2016-06-13 01:54 UTC
Hi,

I'm trying to use the bridge feature with a Dexcom G5 and a EU account. I created an account on https://store.dexcom.com/user/register and enabled sharing in the iOS app. It's working on the Dexcom follow app. Yet, after one hour there is no value on nightscout.
`BRIDGE_SERVER` is set to `EU` and I'm using `0.8.4`.
##

**Comment by martijnmcb** [comment] 2016-07-10 21:24
If you are outside of the U.S.: On the next blank line, type BRIDGE_SERVER. In the box next to it, enter EU.

**Comment by Kdisimone** [comment] 2018-02-20 23:26
I believe this issue can be closed, unless updated with additional information.  EU accounts are supported through BRIDGE_SERVER set to EU.

**Comment by PieterGit** [comment] 2018-02-21 06:57
Fixed, duplicate of https://github.com/nightscout/cgm-remote-monitor/issues/1471
@berpj Please report back if this issue has been fixed for you. Closing this issue for now. If you have problems, please create a new issue and link it to this one.

**Closed by PieterGit** 2018-02-21 06:57 UTC
