### ISSUE TITLE
Wrong API secret

### ISSUE THREAD

**Issue by Diabeast** [nightscout/cgm-remote-monitor#4659] opened 2019-05-28 17:09 UTC
I am having a lot of trouble with Herokuapp, I tried everything and still i get api secret wrong notice. My Mlab Entries are empty and i deployed a whole new app wich didn't solved the problem. PLEASE HELP

**Comment by unsoluble** [comment] 2019-05-28 20:36
The API secret failing is often simply an indication that your app has crashed. Try this: Restart your dynos in Heroku, and immediately open your logs. Try to capture the moment your app changes from running to crashed — if you can copy or screenshot the surrounding context, we can help identify the cause.

**Comment by wepliny** [comment] 2019-10-09 09:57
Authentication failed. {status: 200, message: "UNAUTHORIZED"}
hashauth.js:137 ƒ verifyAuthentication(next) {
    hashauth.authenticated = false;
    $.ajax({
      method: 'GET'
      , url: '/api/v1/verifyauth?t=' + Date.now() //cache buster
      , headers: client.headers…

**Comment by wepliny** [comment] 2019-10-09 10:01
(eval $(cat my.env | sed 's/^/export /') && PORT=1337 node server.js)  
this is my startup code


CUSTOMCONNSTR_mongo=mongodb://admin:123456@127.0.0.1:27017/admin
CUSTOMCONNSTR_mongo_collection=entries
MONGO_PROFILE_COLLECTION=profile
API_SECRET=LONGAPISECRETSTRING
HOSTNAME=127.0.0.1
ENABLE=careportal%20basal%20bwp%20iob%20cob%20cage%20sage%20iage
SHOW_PLUGINS="rawbg-on careportal upbat iob profile cage cob basal avg treatments boluscalc pump openaps iage speech"
DISPLAY_UNITS="mmol"
TIME_FORMAT=24
ALARM_TYPES="predict"
LANGUAGE=zh_cn
INSECURE_USE_HTTP=true
PORT=1337
NODE_ENV=development

**Comment by unsoluble** [comment] 2019-10-09 14:20
@wepliny That's not a crashed app, that's an actual authentication failure.

**Comment by wepliny** [comment] 2019-10-09 15:25
Where is the setting API_SECRET?

**Comment by wepliny** [comment] 2019-10-09 15:27
my url http://cgm.u-x.cn
please help me

**Comment by unsoluble** [comment] 2019-10-09 15:36
`API_SECRET` is a config variable, normally set through the Heroku interface. If you're hosting your own site, can't really help with the details.

**Comment by wepliny** [comment] 2019-10-09 15:41
My CGM use centos config , How to config the API_SECRET,or please recommend me see configuration method, I can't login my NC system, you can access (http://cgm.u-x.cn), I have carried out the command

(eval $(cat my.env | sed 's/^/export /') && PORT=1337 node server.js)

**Comment by unsoluble** [comment] 2019-10-09 15:43
This isn't really a support forum. Try over in [Gitter](https://gitter.im/nightscout/cgm-remote-monitor) or [Discord](https://discordapp.com/invite/zg7CvCQ).

**Comment by wepliny** [comment] 2019-10-09 15:46
Thank you very much, to learn from you

**Comment by bwclarke** [comment] 2019-10-13 16:29
After updating my branch I’m having a similar issue with API secret saying it’s wrong when it isnt and the app keeps crashing. Have a log I can share. I’m using the default Heroku URL though

**Comment by unsoluble** [comment] 2019-10-13 16:30
@bwclarke Please get in touch over on Gitter or Discord, as mentioned above.

**Comment by PieterGit** [comment] 2019-10-17 06:05
@Diabeast Closing issue. This seems a support question and not a bug/defect. Please use Discord for that as mentioned by @unsoluble

**Closed by PieterGit** 2019-10-17 06:05 UTC
