### ISSUE TITLE
Alexa plugin error

### ISSUE THREAD

**Issue by apocsantos** [nightscout/cgm-remote-monitor#5632] opened 2020-04-24 23:27 UTC
**Describe the bug**
Alexa plugin does not work, it keeps returning "i'm not sure about that"

**To Reproduce**
1. Go to 'test in alexa skills'
2. Click on 'type: "ask Nightscout how am I doing" '
3. returns "i'm not sure about that"

**Expected behavior**
reply with my current nightscout blood glucose level.

**Your setup information**
- What version of Nightscout Updated this week
- What type of CGM, and how do you get your data there? (miaomiao)

**Additional context**

**Comment by inventor96** [comment] 2020-04-27 07:27
Both Amazon Alexa and Google Assistant don't play well with the name when we use the one-word version "Nightscout". Try separating it, like "night scout" both in your invocation name, as well as in what you type in the testing page.

**Comment by apocsantos** [comment] 2020-04-27 12:34
Hi,
Thank you!

Tried that but no luck it replies: "There was a problem with the requested skill's response" to the question :  "ask night scout how am I doing".

Here is my Json Skill Code


`{
    "interactionModel": {
        "languageModel": {
            "invocationName": "night scout",
            "intents": [
                {
                    "name": "NSStatus",
                    "slots": [],
                    "samples": [
                        "How am I doing"
                    ]
                },
                {
                    "name": "LastLoop",
                    "slots": [],
                    "samples": [
                        "When was my last loop"
                    ]
                },
                {
                    "name": "MetricNow",
                    "slots": [
                        {
                            "name": "metric",
                            "type": "LIST_OF_METRICS",
                            "samples": [
                                "what {pwd} {metric} is",
                                "what my {metric} is",
                                "how {pwd} {metric} is",
                                "how my {metric} is",
                                "how much {metric} does {pwd} have",
                                "how much {metric} I have",
                                "how much {metric}",
                                "{pwd} {metric}",
                                "{metric}",
                                "my {metric}"
                            ]
                        },
                        {
                            "name": "pwd",
                            "type": "AMAZON.US_FIRST_NAME"
                        }
                    ],
                    "samples": [
                        "how much {metric} does {pwd} have left",
                        "what's {metric}",
                        "what's my {metric}",
                        "how much {metric} is left",
                        "what's {pwd} {metric}",
                        "how much {metric}",
                        "how is {metric}",
                        "how is my {metric}",
                        "how is {pwd} {metric}",
                        "how my {metric} is",
                        "what is {metric}",
                        "how much {metric} do I have",
                        "how much {metric} does {pwd} have",
                        "how much {metric} I have",
                        "what is my {metric}",
                        "what my {metric} is",
                        "what is {pwd} {metric}"
                    ]
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                }
            ],
            "types": [
                {
                    "name": "LIST_OF_METRICS",
                    "values": [
                        {
                            "name": {
                                "value": "uploader battery",
                                "synonyms": [
                                    "uploader battery remaining",
                                    "uploader battery power"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "pump reservoir",
                                "synonyms": [
                                    "remaining insulin",
                                    "insulin remaining",
                                    "insulin is left",
                                    "insulin left",
                                    "insulin in my pump",
                                    "insulin"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "pump battery",
                                "synonyms": [
                                    "pump battery remaining",
                                    "pump battery power"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "bg",
                                "synonyms": [
                                    "number",
                                    "blood sugar",
                                    "blood glucose"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "iob",
                                "synonyms": [
                                    "insulin on board"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "basal",
                                "synonyms": [
                                    "current basil",
                                    "basil",
                                    "current basal"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "cob",
                                "synonyms": [
                                    "carbs",
                                    "carbs on board",
                                    "carboydrates",
                                    "carbohydrates on board"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "forecast",
                                "synonyms": [
                                    "ar2 forecast",
                                    "loop forecast"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "raw bg",
                                "synonyms": [
                                    "raw number",
                                    "raw blood sugar",
                                    "raw blood glucose"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        "dialog": {
            "intents": [
                {
                    "name": "MetricNow",
                    "confirmationRequired": false,
                    "prompts": {},
                    "slots": [
                        {
                            "name": "metric",
                            "type": "LIST_OF_METRICS",
                            "confirmationRequired": false,
                            "elicitationRequired": true,
                            "prompts": {
                                "elicitation": "Elicit.Slot.1421281086569.34001419564"
                            }
                        },
                        {
                            "name": "pwd",
                            "type": "AMAZON.US_FIRST_NAME",
                            "confirmationRequired": false,
                            "elicitationRequired": false,
                            "prompts": {}
                        }
                    ]
                }
            ],
            "delegationStrategy": "ALWAYS"
        },
        "prompts": [
            {
                "id": "Elicit.Slot.1421281086569.34001419564",
                "variations": [
                    {
                        "type": "PlainText",
                        "value": "What metric are you looking for?"
                    },
                    {
                        "type": "PlainText",
                        "value": "What value are you looking for?"
                    },
                    {
                        "type": "PlainText",
                        "value": "What metric do you want to know?"
                    },
                    {
                        "type": "PlainText",
                        "value": "What value do you want to know?"
                    }
                ]
            }
        ]
    }
}`

**Comment by inventor96** [comment] 2020-04-27 16:47
There's usually a log or at the response from the server on the right side of the testing page. What info is provided there?

**Comment by apocsantos** [comment] 2020-04-27 17:31
Right-Side

`{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.c862a795-f830-4b88-b8bc-1ebc5ace3762",
		"application": {
			"applicationId": "amzn1.ask.skill.f8470ed3-f091-40cf-bec0-b29e1722555f"
		},
		"user": {
			"userId": "amzn1.ask.account.AFPUXHL7VNHDU7GJC36TYW6OTREEGO2Y4CEKXWF62HDRXLS5PDXI7V22DT7BN7K7QJ42YSP7BDHLUZ7NTPC3CP5RHH44UKGET76KQFTDYV4LX3CQSB6GCPFAKQJY3N7O6XRQRDNAFFKFASGLKZ4NJC6CO4XIBPUK4CGVEW2FAU2NZYMH5MR4ZF3HZZ5JUAGSWI2MSDHTXSMPBFQ"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.f8470ed3-f091-40cf-bec0-b29e1722555f"
			},
			"user": {
				"userId": "amzn1.ask.account.AFPUXHL7VNHDU7GJC36TYW6OTREEGO2Y4CEKXWF62HDRXLS5PDXI7V22DT7BN7K7QJ42YSP7BDHLUZ7NTPC3CP5RHH44UKGET76KQFTDYV4LX3CQSB6GCPFAKQJY3N7O6XRQRDNAFFKFASGLKZ4NJC6CO4XIBPUK4CGVEW2FAU2NZYMH5MR4ZF3HZZ5JUAGSWI2MSDHTXSMPBFQ"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AHX2L2PI4X6JD4ZGBJK7JHNZVDMYINEYMLN2YFZOSN5WKQFHZROXNLPY635NG5R6EPF7RX2QOZOJ25MK6REONIBKKOTQGD2LGZIPX4IGZCBMY4FZUIETVW7J4EAGSAVNPLOXW6JJMEUWPARBAMN3LP4O3I5ZD6EHUK42SQJERGI4ZODKVHNU4",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLmY4NDcwZWQzLWYwOTEtNDBjZi1iZWMwLWIyOWUxNzIyNTU1ZiIsImV4cCI6MTU4ODAwODg2MywiaWF0IjoxNTg4MDA4NTYzLCJuYmYiOjE1ODgwMDg1NjMsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQUFEZFphTmxQZkxaaTNEcFE4a0x3YnRiS2dFQUFBQUFBQUE0Q1hiMy9Hdk5aZk45NGt5RTJSTmhmN255Y1pQUmZwTklYOXpWUG9wMWpYbU5zNXJpWXBwNDhCZFJacVJjd0JTcDc0bnpYQXk1cUlNajNrZGNzQ0JUeDFTQTR3VWErKytRenBCcWVDbkkvOXZKNExWZWhic1lpMzJYT0V1bk1mMUw2SDhPRkJWN2pnQVl1MmdyYS9CUUN1dWVQWnc3NVdEb0M0WHMrV0N5ck1XZ0REcWwyNU9NZTNEL3V4SDZ1K1h5WWlwTTVOd1VQdzhaTWo3UlhFcW9rbDAxQ3dlVXk5ZVhCZDU4eTR1Ui9jc2RoZFFKZEhiYnlGTnRVVEJybXJiTkMrYi9lMDZ4N2FuNkY5UUtyTi9DM043bUFlWmVBNGU2QU9CQWtMUGFJMzdFSjJnVjlTWWRoSm9QWVhIbGgrRmpMR0grMll2Ukp1SDBTdWs4dDV1VDNSUDFJcFVkRFdHZUJuVmljSjJ0WjNTOUdYTWhiSTl5bXNZV3pCdXpTVG8wVUNpUUlMVnRZZkFDIiwiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUhYMkwyUEk0WDZKRDRaR0JKSzdKSE5aVkRNWUlORVlNTE4yWUZaT1NONVdLUUZIWlJPWE5MUFk2MzVORzVSNkVQRjdSWDJRT1pPSjI1TUs2UkVPTklCS0tPVFFHRDJMR1pJUFg0SUdaQ0JNWTRGWlVJRVRWVzdKNEVBR1NBVk5QTE9YVzZKSk1FVVdQQVJCQU1OM0xQNE8zSTVaRDZFSFVLNDJTUUpFUkdJNFpPREtWSE5VNCIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFGUFVYSEw3Vk5IRFU3R0pDMzZUWVc2T1RSRUVHTzJZNENFS1hXRjYySERSWExTNVBEWEk3VjIyRFQ3Qk43SzdRSjQyWVNQN0JESExVWjdOVFBDM0NQNVJISDQ0VUtHRVQ3NktRRlREWVY0TFgzQ1FTQjZHQ1BGQUtRSlkzTjdPNlhSUVJETkFGRktGQVNHTEtaNE5KQzZDTzRYSUJQVUs0Q0dWRVcyRkFVMk5aWU1INU1SNFpGM0haWjVKVUFHU1dJMk1TREhUWFNNUEJGUSJ9fQ.cehFjw2OXNgzukRybcBmiSObebaYYHXfQXyoFygccps5x1QLF91tusqaXW3irYmxzhLeLLvU02IZEac-zslan8_FhBcew-FWo1jLdamarUJZVb8ACZRpYdBYyV7LFxn1FlZYNbLai0ixKSokbaZIBiqpPfk4JWIh-tVjEHC2JK3eQ0BbGOSw-Tjyo2cH5qzBGxEInSSj5XGgPZqjVYBOwOzCLTg7ClNw9Mum16dyM5YVEXhreXG0IJAstCje5UxRIj4O91O6dnB8WdCqTK-GX9PRVyKzkNRRZCCGXEBRuPaNupeyd4vPDY0SE3NezTLRaIfEROG9KYgL3490jPjHfA"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 160,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1024,
							"pixelHeight": 600
						}
					}
				}
			}
		]
	},
	"request": {
		"type": "SessionEndedRequest",
		"requestId": "amzn1.echo-api.request.8decd029-81e4-4f1d-bfde-479156475fe1",
		"timestamp": "2020-04-27T17:29:24Z",
		"locale": "en-US",
		"reason": "ERROR",
		"error": {
			"type": "INVALID_RESPONSE",
			"message": "An exception occurred while dispatching the request to the skill."
		}
	}
}`

Right side, nothing :(

**Comment by inventor96** [comment] 2020-04-27 17:42
Hmm... You've set your site URL, right?

https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md#point-your-skill-at-your-site

**Comment by apocsantos** [comment] 2020-04-27 20:33
Guess so

Service Endpoint Type: HTTPS

Default Region
(Required)
https://nightscout-nightowl.herokuapp.com/api/v1/alexa

**Comment by inventor96** [comment] 2020-04-28 09:53
We usually try to keep individual URLs private, so feel free to delete your
message with your URL.

With that being said, now that I have it via email, are you OK if I try
simulating Alexa contacting your Nightscout site to help troubleshoot the
issue?

**Comment by inventor96** [comment] 2020-04-28 09:54
We usually try to keep individual URLs private, so feel free to delete your message with your URL.

With that being said, now that I have it via email, are you OK if I try simulating Alexa contacting your Nightscout site to help troubleshoot the issue?

**Comment by apocsantos** [comment] 2020-04-28 13:22
Hi,
Thank you so much!

Sure, feel free to try, I dont mind at all!

**Comment by apocsantos** [comment] 2020-05-05 23:41
Hi!
Any news ?

**Comment by inventor96** [comment] 2020-05-06 05:05
Sorry for the delay. I am in the process of moving to a different house, so
I haven't got to it yet.

**Comment by julianhansen** [comment] 2020-05-20 13:57
A simple solution is to use Sugarmate, I have added an Echo Button so can get a BG update during the night without needing to look at my phone or ask Alexa a question.

**Comment by inventor96** [comment] 2020-06-09 04:42
@apocsantos So sorry for the delay in helping you. When manually simulating the request that Alexa makes to Nightscout, I got the error `Cannot POST /api/v1/alexa`, which usually means that the plugin isn't enabled. Could you check that your "ENABLE" variable in Heroku (or Asure, if that's what you use) includes "alexa" (no quotes, and spaces between each plugin name).

**Comment by apocsantos** [comment] 2020-06-15 21:45
@inventor96 , sorry for the late reply, I've been a bit busy this last week.

Just checked it, it's just like in the image.


![Screenshot 2020-06-15 22 40 30](https://user-images.githubusercontent.com/1417821/84709261-c927cb80-af59-11ea-9024-f132a8578b5a.png)

**Comment by inventor96** [comment] 2020-06-16 06:40
@apocsantos It's supposed to be the other way around... Like this:
![image](https://user-images.githubusercontent.com/7132744/84739936-ba491500-af69-11ea-8399-8230c168fb1f.png)

You have an `ENABLE` variable which contains the names of the plugins to enable on your Nightscout site. Each plugin name is separated by a space.

**Comment by apocsantos** [comment] 2020-06-16 10:25
@inventor96 , oh... Sorry! Guess it's correct now.

Can you please check if this is it ?

![alexa](https://user-images.githubusercontent.com/1417821/84763353-f4df9b80-afc3-11ea-9cb1-ea109236549a.PNG)

**Comment by inventor96** [comment] 2020-06-16 21:18
@apocsantos That looks correct. Test your Alexa skill and see what happens!

**Comment by apocsantos** [comment] 2020-06-16 22:27
@inventor96 ,
Tested it, no luck, same as before... :(

**Comment by inventor96** [comment] 2020-06-16 22:44
@apocsantos I'm getting a different error now, but it looks like the plugin has been enabled properly. I will need to do some further troubleshooting to figure out where the issue is.

**Closed** 2020-11-15 09:09 UTC
