### ISSUE TITLE
"Day to day" Report does not show requested days and is stuck in "Rendering"

### ISSUE THREAD

**Issue by 2flea** [nightscout/cgm-remote-monitor#3659] opened 2018-07-02 07:00 UTC
![image](https://user-images.githubusercontent.com/38214111/42149074-f92077dc-7dd4-11e8-81a6-df116dc98c2b.png)

Since some days I cannot run the "day to day" reports any longer for a date range. It does not show all days requested but stops in "Rendering" status. Screenshot is for last 2 days but this happens also for last week or last 2 weeks. All days except the last or last two are rendered and shown correctly. 

This worked successfully before but since two days I have this issue - maybe it is data related?!

Nightscout
version 0.10.2-release-20171201
head

Browser tested: 
Chrome Version 67.0.3396.99 (Offizieller Build) (64-Bit)
Firefox Version 61.0 (64-Bit)
Safari Version 11.1.1

**Comment by 2flea** [comment] 2018-07-02 10:37
Seems to be related with profile switches. I switched on 29.06. and on 01.07. and if one of these days is in the report range this issue occurs.

**Comment by sulkaharo** [comment] 2018-07-08 12:01
Can you retry with latest test please?

**Comment by 2flea** [comment] 2018-07-08 18:54
Tried latest dev branch without success.

<img width="299" alt="screenshot 2018-07-08 20 52 16" src="https://user-images.githubusercontent.com/38214111/42422950-09069674-82f1-11e8-9ee2-2f91df28dad6.png">
<img width="449" alt="screenshot 2018-07-08 20 52 35" src="https://user-images.githubusercontent.com/38214111/42422951-0923c9c4-82f1-11e8-9bc1-a1291334c26f.png">

**Comment by PieterGit** [comment] 2018-07-08 20:36
@2flea can you tell me which Node version you are using and what kind of hosting (Azure, Heroku, Self hosted, etc.)

**Comment by PieterGit** [comment] 2018-07-08 20:37
Tagging this for 0.10.3 version, but because this will be released soon, this might not make it in time.

**Comment by 2flea** [comment] 2018-07-09 11:37
Heroku hosting:
~/node_modules $ npm version
{ Nightscout: '0.10.2-release-20171201',
  npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  **node: '8.9.4',**
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }

**Comment by sulkaharo** [comment] 2018-07-09 11:48
If the process gets stuck on Rendering, that should mean the client has successfully loaded all the data and gets stuck on some data issue. Can you open the Javascript console on your browser when you get this, and see if there's errors logged?

**Comment by 2flea** [comment] 2018-07-09 11:53
There is the following error displayed from "profilefunctions.js" line 266

![image](https://user-images.githubusercontent.com/38214111/42448902-1976bb0e-837f-11e8-89f2-70a33901dfe4.png)

On 01.07. I did a profile switch, if I include this day I get the above problem/error, if I exclude it no problem with the displaying.

**Comment by quizzmaster** [comment] 2018-07-18 09:57
I'm using version **0.10.3-dev-20180708** getting the following error if a profile switch occured within a requested day:
`TypeError: e is undefined  bundle.js:16:684377`

**Comment by PieterGit** [comment] 2018-08-05 09:58
Can you retry with the 0.10.3 release. We didn't make it fixing this for the 0.10.3 release. Let's see if we can fix this with Nightscout 0.11

**Comment by 2flea** [comment] 2018-08-05 11:51
Master 0.10.3 did not fix it. I tried 0.10.3 dev before also without success.

**Comment by viq** [comment] 2018-09-29 20:59
I can confirm I'm still seeing something at least very similar on today's `dev`.

**Comment by Unvollendet8** [comment] 2018-10-14 14:45
Is there a workaround for that? Because I'm experiencing the exact same problem and I did a lot profile switches the last days for different reasons.

**Comment by PieterGit** [comment] 2018-10-14 21:46
@Unvollendet8  I don't know of any workaround and don't have the possibility to do profileSwitches at this moment.

The error @2flea lists in https://github.com/nightscout/cgm-remote-monitor/issues/3659#issuecomment-403453553 comes from this line:
https://github.com/nightscout/cgm-remote-monitor/blame/dev/lib/profilefunctions.js#L266
which has been in the code for over a year. Perhaps @MilosKozak can help us out what's wrong with the profileswitches.

**Comment by vickster1** [comment] 2018-10-15 11:32
I’m seeing something similar, but with other weird behaviour. My site keeps being unresponsive, so trying to edit my profile takes forever & sometimes I can’t get the new values to load at all. My homepage keeps briefly showing the correct TBR data from AAPS, but then flicks back to a page showing only very recent TBR data & otherwise showing my standard basal profile.
With reports, I tried picking the last month’s data to view day by day. It took a long time to respond & then the date range reverted to the last week & only today & yesterday were shown. At this point the ‘show’ button has disappeared, so even if I try to change the date range or report type, I can’t. Whatever date range I try, it reverts back to the last week. Distribution doesn’t work at all.
Have any other users noticed this other odd behaviour associated with the reports issue?

**Comment by 2flea** [comment] 2018-10-24 18:28
@PieterGit how do I update to Node 8.12.0?

**Comment by 2flea** [comment] 2018-10-24 18:45
@PieterGit just tested with latest dev "0.11.0-dev-20181022" including Node 8.12.0. I cannot reproduce the issue neither. I ran the day-to-day report for the time from 01.07.2018 till today which includes several profile switches (Original problem was 01.07.2018-02.07.2018). The report appears after some time with all days displayed. Looks OK to me.

**Comment by PieterGit** [comment] 2018-10-24 19:18
@2flea thanks for the report. I looked to all the changes, see https://github.com/nightscout/cgm-remote-monitor/pull/4022/files . Perhaps it was caused by  `"mongodb": "~3.0.11"`, which is now upgraded to `"mongodb": "^3.1.8"`` 

I hope others can confirm this is fixed for the upcomping 0.11 release. Otherwise, we need to dig deeper.

**Comment by Unvollendet8** [comment] 2018-10-25 18:45
@PieterGit thanks for the testing. I'd like to give some feedback as well, but I don't know how to update to the latest dev. Sorry. Is there any wiki where I can find it? Thanks in advance.

**Comment by vickster1** [comment] 2018-10-29 12:05
I'm using Dex G5, AAPS master 1.58, xdrip latest master 2018.09.08, Dana RS & heroku. I don't have experience in computer science, so don't tend to test any dev versions. I'm using Nighscout v0.10.3-master-20180805. 
I know how to update to the latest dev, but don't know how to check my Node number or change it.
I have Node.js listed as my framework on my heroku dashboard, but no number.

**Comment by 2flea** [comment] 2018-10-29 12:20
> I know how to update to the latest dev, but don't know how to check my Node number or change it.
You need to open the console in Heroku and open a bash shell. Then type "npm version". 
If you'd upgrade to latest dev it would include the update of node.js .

**Comment by sulkaharo** [comment] 2018-10-29 20:43
https://github.com/nightscout/cgm-remote-monitor/pull/4031 might fix this - if you can pull the PR and test, that'd be awesome

**Comment by sulkaharo** [comment] 2018-10-29 21:00
@PieterGit Debugged this with one user and for her the issue was a Profile Change event that didn't have a profile at all, causing a crash on the line I if'd out ^^

**Comment by sulkaharo** [comment] 2018-10-30 08:38
I pushed the fix to DEV branch - if everyone here could test if the reporting works now and write back, that'd be awesome

**Comment by neothem** [comment] 2018-10-30 18:12
> I pushed the fix to DEV branch - if everyone here could test if the reporting works now and write back, that'd be awesome

Thank you very much mate, everything is working fine now!

I had the same problems as stated above (using the latest master branch) , deployed the newest dev branch and voilà the "day to day" reports appear in its entirety.

My setup: Dana RS, Dexcom G6, latest dev AAPS, xDrip+ and Nightscout 0.11.0-dev-20181022.

Thanks for the support!

Cheers.

**Comment by sulkaharo** [comment] 2018-10-30 19:16
@neothem do you think you could provide logs from AAPS to @MilosKozak so we could check if the problematic profile events are originating from AAPS?

**Comment by neothem** [comment] 2018-10-30 19:32
@sulkaharo Sure, no problem. Should I send the logs via mail to the stated mail adress which can be found in AAPS under maintenance?

**Comment by vickster1** [comment] 2018-11-01 09:58
I have updated to dev 0.11.0 & can now see reports again - thanks a lot for helping!

But...there are still issues. Do you want me to open a new issue about these?

1. My Nightscout page flicks back & forth between showing all TBRs & only showing TBRs from the last 3 hours (and also not showing sage or cage).
2. Profile edits are very temperamental. The profile edit page is often unresponsive, and I can be part way through a profile edit when the page reverts back to a different profile with no option to change it.
3. After loading a report, the date at the top reverts back to the last 7 days, the ‘show’ button is no longer visible & both ‘day to day’ button and the ‘distribution’ button which I had chosen are both highlighted. To then choose a different report/date I have to reload the page.
![3853f179-d9f7-48bc-ac92-b22f7f669fe1](https://user-images.githubusercontent.com/38795035/47845072-e0816780-ddbb-11e8-8bd9-1b4970e7e3f7.png)
![36788166-b02c-4bb5-9b13-94418a3bfac1](https://user-images.githubusercontent.com/38795035/47845073-e0816780-ddbb-11e8-98fd-e79e16dea41c.png)

**Comment by 2flea** [comment] 2018-11-05 14:04
@PieterGit @sulkaharo Shall/Can I close the issue? Or do you need any more tests and confirmations by other users?

**Comment by sulkaharo** [comment] 2018-11-05 14:13
Given there's a confirmation it's fixed from multiple users, maybe close. If you can create new tickets about the other issues, that'd be great. :)

**Closed** 2018-11-05 14:14 UTC
Labels: help wanted, needs testing

**Comment by candreassen** [comment] 2018-11-05 15:02
I don’t even know what this means. I am trying to set up nightscout in my Apple phone to follow my daughters dexcom

Colleen
