### ISSUE TITLE
Nightscout displays temp targets in the wrong spot

### ISSUE THREAD

**Issue by tomasboudr** [nightscout/cgm-remote-monitor#2530] opened 2017-04-04 11:28 UTC
Here I have a temp target for use with OpenAPS and it displays twice in Chrome. The temp targets at 7 & 8:43AM are real, the third one is a mirage, not sure why its showing another entry later.

**Comment by tomasboudr** [comment] 2017-04-04 11:30
![image](https://cloud.githubusercontent.com/assets/156123/24654651/a1147c32-1908-11e7-8776-74bce47a8244.png)

**Comment by Kdisimone** [comment] 2018-02-20 23:43
usually this is resolved by a refresh.  Has your issue continued?  Or can this issue be closed?

**Comment by tomasboudr** [comment] 2018-02-21 13:08
Yes that fixes it, but it’s still an issue.

**Comment by PieterGit** [comment] 2018-02-26 20:02
@tomasboudr Yes, I've seen this as well. If you can try to find more information about when this occurs please share this. I'm setting this for the 0.11.0 release, because this issue will probably not be fixed in the next weeks.

**Comment by PieterGit** [comment] 2018-10-25 12:20
@tomasboudr I haven't reproduced this with Nightscout 0.11-dev. Can you tell me what Nightscout version you experienced this with? Can you switch to the `dev` version and see if you can reproduce it there?

**Comment by PieterGit** [comment] 2019-02-03 00:48
@tomasboudr  can you confirm that you can still reproduce this issue with 0.11-dev branch. If not, I need to close this issue due to inactivity.

**Comment by tomasboudr** [comment] 2019-02-03 12:57
It appears fixed.

**Closed** 2019-02-03 14:08 UTC
