### ISSUE TITLE
basal pill pop-up info provides wrong sensitivity value

### ISSUE THREAD

**Issue by vonstein2002** [nightscout/cgm-remote-monitor#5423] opened 2020-01-06 16:04 UTC
Nightscout ver: 13.0.1

When hoovering over basal pill, pop-up info for "Sensitivity" is incorrect.  It is 18 times the actual value.  ie: my sensitivity is 78mg/dL/U... the basal pill pop-up shows 1404mg/dL/U

this is occurring on 2 different Nightscout sites and 2 different browsers(Edge and Chrome).  Also occurs on Chrome/Android

All other info in the pop-up is accurate.

**Comment by vonstein2002** [comment] 2020-01-07 22:14
Just noticed the same issue with treatment pop-ups that include a BG value, it's 18 times the actual sensor value

**Comment by jakobsandberg** [comment] 2020-01-07 22:53
"it's 18 times the actual sensor value" - this sounds like an issue with glucose density units, as 18 is the scaling factor to convert from mmol/l to mg/dl.

I can take a look at this right now

**Comment by jakobsandberg** [comment] 2020-01-08 00:32
This was actually fixed in 8139cb9 but has not yet been released

**Comment by pbudzon** [comment] 2020-05-25 12:44
I can confirm this is still present in current master.

**Comment by bjornoleh** [comment] 2020-06-15 09:46
The bug also affects users with mmol/L units, in both Master and Dev.

With mmol/L units, I get ISF 0,6 mmol/U in the basal pill. The sensitivity is actually 10 mmol/U. So there seems to be a mismatch in the convertsion between units.

My case, mmol/L: 10/18=0,6
(Current Dev branch, Release 13.1.0 #5526)

Someone elses case, reported in Looped FB, mg/dL: 110*18=1980 
(unknown version)

**Closed** 2021-02-14 10:24 UTC
