### ISSUE TITLE
Azure hosting: npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

### ISSUE THREAD

**Issue by eugman** [nightscout/cgm-remote-monitor#3535] opened 2018-04-29 15:04 UTC
Trying to deploy the latest version to Azure and I get the following error page:

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Using start-up script server.js from package.json.
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 6.12.3, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3, 8.9.4, 8.10.0, 8.11.1.
Selected node.js version 8.9.4. Use package.json file to choose a different version.
Selected npm version 5.3.0
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN invalid config scripts-prepend-node-path="--production"
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
Thread was being aborted.
Thread was being aborted.

**Comment by PieterGit** [comment] 2018-06-27 17:57
@eugman thanks for the report.

This warning can be ignored. It's caused by a dependency. Setting this to milestone for the next release (0.11). We should not only fix these warnings, but also make sure that all dependencies are published on npm repository.

**Comment by PieterGit** [comment] 2018-10-23 18:36
Fix in https://github.com/mddub/minimed-connect-to-nightscout/pull/7 
Closing issue

**Closed by PieterGit** 2018-10-23 18:36 UTC
Labels: upstream bug
