### ISSUE TITLE
Bolus Wizard & Food entries

### ISSUE THREAD

**Issue by mdomox** [nightscout/cgm-remote-monitor#3520] opened 2018-04-20 21:00 UTC
Since I updated to the current master version, I cannot quickpick or add from database food when using Bolus Wizard. Food editor works fine, though.

This is a new bug. It happens all the time, with all browsers (even mobile). 

![screenshot_1](https://user-images.githubusercontent.com/2255012/39073516-b9c34928-44f6-11e8-9704-a4514d9d9966.png)

**Comment by Cloclo51** [comment] 2018-07-07 13:45
Hello,
I have the same problem. Did you find an solution?

**Comment by PieterGit** [comment] 2018-07-11 05:40
@Cloclo51 and @mdomox Can you check if this is reproducible with the `dev` branch? We're about to release 0.10.3 release.

**Comment by Cloclo51** [comment] 2018-07-11 05:58
Hello Pieter

 

Thank you for your answer. I’m quite new with nightscout. I try to understand how in works…..

 

I now changed in github from “master” to “dev”. The result is the same. I also started debug. Maybe you see something….

 

https://i.gyazo.com/dcbd23f067e808c079c218c96833c9d8.png

 

Thank you for your help….

 

Regards

Claude

 

 

 

Von: PieterGit [mailto:notifications@github.com] 
Gesendet: Mittwoch, 11. Juli 2018 07:40
An: nightscout/cgm-remote-monitor
Cc: Cloclo51; Mention
Betreff: Re: [nightscout/cgm-remote-monitor] Bolus Wizard & Food entries (#3520)

 

@Cloclo51 <https://github.com/Cloclo51>  and @mdomox <https://github.com/mdomox>  Can you check if this is reproducible with the dev branch? We're about to release 0.10.3 release.

**Comment by PieterGit** [comment] 2018-07-12 22:58
@Cloclo51  or @mdomox 
I managed to reproduce this. It seems to be caused by the fact that a `PUT` on 
`/api/v1/food/ ` leads to a `500 (Internal Server Error)`. This is caused by `foodSubmit` call.

A server code 500 means there is something in the server log (also called console). In my case:

```
2018-07-12T22:49:10.084304+00:00 app[web.1]: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
2018-07-12T22:49:10.084308+00:00 app[web.1]:     at new ObjectID (/app/node_modules/bson/lib/bson/objectid.js:50:11)
2018-07-12T22:49:10.084309+00:00 app[web.1]:     at Function.save (/app/lib/server/food.js:14:15)
2018-07-12T22:49:10.084312+00:00 app[web.1]:     at /app/lib/api/food/index.js:59:18
2018-07-12T22:49:10.084313+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-07-12T22:49:10.084314+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2018-07-12T22:49:10.084316+00:00 app[web.1]:     at check (/app/lib/authorization/index.js:182:9)
2018-07-12T22:49:10.084332+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-07-12T22:49:10.084334+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2018-07-12T22:49:10.084335+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2018-07-12T22:49:10.084337+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-07-12T22:49:10.089107+00:00 heroku[router]: at=info method=PUT path="/api/v1/food/" host=xxx.herokuapp.com request_id=xxx fwd="xxx" dyno=web.1 connect=1ms service=13ms status=500 bytes=1026 protocol=https
```

Can you indicate which version of Nihgtscout this used to work? I'm labelling this a bug/regression/help wanted, and targetting it for 0.10.3 for now. I'm not sure if it will make it, so in that case it might be postponed until the next 0.10.4 or 0.11 release.

**Comment by Cloclo51** [comment] 2018-07-13 00:36
Hello Pieter

 

 

I use version 0.10.2. It ist he first time I use nigtscout so I cannot tell you if it would work with an older version.

 

When you can explain me how I can change to a lower version I will try to do it.

 

Regards

Claude

 

PS: Sorry for my English….. 

 

 

Von: PieterGit [mailto:notifications@github.com] 
Gesendet: Freitag, 13. Juli 2018 00:59
An: nightscout/cgm-remote-monitor
Cc: Cloclo51; Mention
Betreff: Re: [nightscout/cgm-remote-monitor] Bolus Wizard & Food entries (#3520)

 

@Cloclo51 <https://github.com/Cloclo51>  or @mdomox <https://github.com/mdomox> 
I managed to reproduce this. It seems to be caused by the fact that a PUT on
/api/v1/food/ leads to a 500 (Internal Server Error). This is caused by foodSubmit call.

A server code 500 means there is something in the server log (also called console). In my case:

2018-07-12T22:49:10.084304+00:00 app[web.1]: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
2018-07-12T22:49:10.084308+00:00 app[web.1]:     at new ObjectID (/app/node_modules/bson/lib/bson/objectid.js:50:11)
2018-07-12T22:49:10.084309+00:00 app[web.1]:     at Function.save (/app/lib/server/food.js:14:15)
2018-07-12T22:49:10.084312+00:00 app[web.1]:     at /app/lib/api/food/index.js:59:18
2018-07-12T22:49:10.084313+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-07-12T22:49:10.084314+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2018-07-12T22:49:10.084316+00:00 app[web.1]:     at check (/app/lib/authorization/index.js:182:9)
2018-07-12T22:49:10.084332+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-07-12T22:49:10.084334+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2018-07-12T22:49:10.084335+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2018-07-12T22:49:10.084337+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-07-12T22:49:10.089107+00:00 heroku[router]: at=info method=PUT path="/api/v1/food/" host=xxx.herokuapp.com request_id=xxx fwd="xxx" dyno=web.1 connect=1ms service=13ms status=500 bytes=1026 protocol=https

Can you indicate which version of Nihgtscout this used to work? I'm labelling this a bug/regression/help wanted, and targetting it for 0.10.3 for now. I'm not sure if it will make it, so in that case it might be postponed until the next 0.10.4 or 0.11 release.

**Comment by PieterGit** [comment] 2018-07-13 05:11
@mdomox can you tell if you know a Nightscout version in which this worked?

@Cloclo51 i would not recommend installing an older version. I think this bug can be fixed quite soon, but I wasn't able to do it yesterday. Perhaps I can fix it this weekend. 

Can you both confirm you see the same stacktrace in your console?

**Comment by Cloclo51** [comment] 2018-07-13 05:34
Hello Pieter

 

I see this:

 

Consol on the main page

 

 

Nightscout bundle ready bundle.source.js:34

Application got ready event client.js:9:2

Application appears to be online index.js:60

Authentication passed. hashauth.js:29

status isAuthenticated 

Object { apisecret: "", storeapisecret: false, apisecrethash: "APISECRETHASHHERE", authenticated: true, initialized: true, init: init()

, verifyAuthentication: verifyAuthentication(), injectHtml: injectHtml(), initAuthentication: initAuthentication(), removeAuthentication: removeAuthentication()

, … }

hashauth.js:164

Client connected to server. index.js:932

OpenAPS Prefs: 

Object { fields: (5) […], retroFields: (5) […], warn: 30, urgent: 60, enableAlerts: undefined }

openaps.js:49

Prefs: 

Object { warn: 30, urgent: 60, enableAlerts: undefined }

loop.js:32

Client rights:  

Object { read: true, write: true, write_treatment: true }

index.js:942

Die Verbindung zu wss://claudeglimp.herokuapp.com/socket.io/?EIO=3&transport=websocket&sid=5TFcvq9akHbQmrjoAAAQ wurde unterbrochen, während die Seite geladen wurde. universalModuleDefinition:3

Client connected to server. index.js:932

Client rights:  

Object { read: true, write: true, write_treatment: true }

 

On Food-Page

 

Nightscout bundle ready bundle.source.js:34

Application got ready event client.js:9:2

Application appears to be online index.js:60

Authentication passed. hashauth.js:29

status isAuthenticated 

Object { apisecret: "", storeapisecret: false, apisecrethash: "APISECRETHASHHERE", authenticated: true, initialized: true, init: init()

, verifyAuthentication: verifyAuthentication(), injectHtml: injectHtml(), initAuthentication: initAuthentication(), removeAuthentication: removeAuthentication()

, … }

hashauth.js:164

Client connected to server. index.js:932

OpenAPS Prefs: 

Object { fields: (5) […], retroFields: (5) […], warn: 30, urgent: 60, enableAlerts: undefined }

openaps.js:49

Prefs: 

Object { warn: 30, urgent: 60, enableAlerts: undefined }

loop.js:32

Client rights:  

Object { read: true, write: true, write_treatment: true }

index.js:942

Die Verbindung zu wss://claudeglimp.herokuapp.com/socket.io/?EIO=3&transport=websocket&sid=5TFcvq9akHbQmrjoAAAQ wurde unterbrochen, während die Seite geladen wurde. universalModuleDefinition:3

Client connected to server. index.js:932

Client rights:  

Object { read: true, write: true, write_treatment: true }

index.js:942

Document now visible, updating - Fri Jul 13 2018 07:23:54 GMT+0200 index.js:825

Document now visible, updating - Fri Jul 13 2018 07:24:50 GMT+0200 index.js:825

Insulin calculation result:  

Object { profile: "Default", eventTime: Date 2018-07-13T05:25:02.902Z, targetBGLow: 4, targetBGHigh: 6, isf: 0.5, ic: 1.5, iob: 8.43, cob: 0, insulincob: 0, bg: 0, … }

boluscalc.js:469

Food database loaded boluscalc.js:637

retro not fresh load started 

Date 2018-07-13T05:25:10.797Z

index.js:912

retro already loading, started 

Date 2018-07-13T05:25:10.797Z

index.js:906

retro already loading, started 

Date 2018-07-13T05:25:10.797Z

index.js:906

got retroUpdate 

Object { devicestatus: [] }

Date 2018-07-13T05:25:01.316Z

**Comment by mdomox** [comment] 2018-07-29 20:11
@PieterGit , Sorry for my late reply. It worked up till the Habanero update. During Grilled Cheese it was working...

**Comment by mdomox** [comment] 2018-08-01 06:09
The isuue is within boluscalc.js in client.sbx.data.food . Used from last working version,instead and it works: 

boluscalc.loadFoodDatabase = function loadFoodDatabase(event, callback) {
categories = [];
foodlist = [];
$.ajax('/api/v1/food/regular.json', {
headers: client.headers()
, success: function (records) {
records.forEach(function (r) {
foodlist.push(r);
if (r.category && !categories[r.category]) {
categories[r.category] = {};
}
if (r.category && r.subcategory) {
categories[r.category][r.subcategory] = true;
}
});
databaseloaded = true;
console.log('Food database loaded');
fillForm();
}
}).done(function() { if (callback) { callback(); } });
maybePrevent(event);
};

**Comment by PieterGit** [comment] 2018-08-01 06:32
@mdomox good debugging!

I traced it to this commit:
https://github.com/nightscout/cgm-remote-monitor/commit/3457de5b7ebc52126e4d6acf06e6aca95b63db68#diff-9588707d0e165e8b2ba9014e1668b6e5

@MilosKozak can you help fix this regression?

**Comment by mdomox** [comment] 2018-08-01 13:30
@PieterGit Till this is permanently fixed, why don't you revert this commit that caused this break in functionality?

**Comment by PieterGit** [comment] 2018-08-01 21:48
@mdomox because I'm sure @MilosKozak had a goal with his change and several other things have changed since then. So going back is not always the best solution for fixing a problem. I'm pretty sure @MilosKozak will join this issue in a couple of days, and reverting stuff I don't understand can cause other issues that I'm unaware of.

**Comment by PieterGit** [comment] 2018-08-02 23:46
@mdomox See my reaction on https://gitter.im/nightscout/public?at=5b632d926d45752f987d1cff

If you test the revert of the commit mentioned above, and test it, I think we can merge it to dev and perhaps we make it for the 0.10.3 release. I don't have time to test this regression and I don't know or use the food feature. Probably not many people use it, because your the first one to report that it's broken.

If @MilosKozak has time to look at this issue, that would be great, because he has done most on this feature and created the commit that caused your regression.

**Comment by MilosKozak** [comment] 2018-08-03 07:46
food has been added to sbx some time ago.so making another GET is wasting. i probably didn't it well . anyone looked where is the problem?

**Comment by mdomox** [comment] 2018-08-03 08:35
@pieterGit In my dev branch I updated bolucalc with the old one and now importing from food database to bolulcalc works. Functionality has been restored. I believe that if the sbx issue is not resolved by 0.10.3 release, using the old boluscalc.js will result in a working version with no broken food functionality.

**Comment by Cloclo51** [comment] 2018-08-04 06:36
Hello mdomox,

 

can you help me to update boluscalc with an older version. As a newbie I have no idea what to do…. I have “version 0.10.3-dev-20180624“

 

Regards

Cloclo

 

 

Von: mdomox [mailto:notifications@github.com] 
Gesendet: Freitag, 3. August 2018 10:36
An: nightscout/cgm-remote-monitor
Cc: Claude Fracheboud; Mention
Betreff: Re: [nightscout/cgm-remote-monitor] Bolus Wizard & Food entries (#3520)

 

@PieterGit <https://github.com/PieterGit>  In my dev branch I updated bolucalc with the old one and now importing from food database to bolulcalc works. Functionality has been restored. I believe that if the sbx issue is not resolved by 0.10.3 release, using the old boluscalc.js will result in a working version with no broken food functionality.

**Comment by PieterGit** [comment] 2018-08-04 10:28
@mdomox @Cloclo51 
I created a branch with the reverted `boluscalc.js` file. See https://github.com/PieterGit/cgm-remote-monitor/tree/201808_food_3520  .  If you deploy that branch, you have the files.
All unit test pass with this branch.

Unfortunately I see some problems when I browse to `/food `
- It doesn't work
- I see a `Status: Error` at the top
- I still see `/api/v1/food/ 500 (Internal Server Error)` on the `/food` page when I submit entries 
- I can't figure out how to add Category and Subcategories

If we can't make it work on dev I would propose to postpone fixing this to 0.11 release

**Comment by PieterGit** [comment] 2018-08-04 11:58
@mdomox @Cloclo51
I found a much better fix, see https://github.com/nightscout/cgm-remote-monitor/pull/3768 or use
https://github.com/PieterGit/cgm-remote-monitor/tree/201808_food2

This fixes the problem with the Object generation and fixes the problem for me. I can add foods (remove ID) and edit foods (click on line and edit it). Can you please test this fix and see if this fixes your problems?

@sulkaharo @MilosKozak : we might check the ObjectID generation /  code in other files as well. Do it now, or postpone until Nightscout 0.11?

![image](https://user-images.githubusercontent.com/6500826/43676274-549c2ff6-97ee-11e8-98c9-9a34f9280611.png)

**Comment by mdomox** [comment] 2018-08-04 18:53
@PieterGit tested food2 branch. No issues! Works great

**Comment by PieterGit** [comment] 2018-08-05 10:00
Fixed with https://github.com/nightscout/cgm-remote-monitor/pull/3768 
Closing issue.

**Closed by PieterGit** 2018-08-05 10:00 UTC
Labels: bug, help wanted, regression

**Comment by hugonluz** [comment] 2024-12-03 11:56
I know that this issue has been closed for a long time ago, but I am having the very same problem now with the Bolus Wizard not showing the quick picks in any of the platforms that I am using (neither Mac OS not iPhone). Is there any trick I am missing?
