### ISSUE TITLE
14.0.5 master could not get Loop data

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6138] opened 2020-09-27 16:36 UTC
I changed to 14.0.5 master today for two NS instances fed with Loop data and CGM via Dexcom Bridge. CGM data was displayed, but no new Loop data was shown in the main screen after updating, even after >20 minutes. The Loop pill (FreeAPS) reported the age of the old Loop data 

I did not yet check reports.

Reverting to Dev 14.0.3 made Loop data load as usual.

**Comment by bjornoleh** [comment] 2020-09-27 17:41
@sulkaharo  I changed one of the NS instances back to 14.0.5 master again, with the same result. Some Loop data are shown in Loop, as far as I can see this is temp basals and boluses, and the COB pill. The IOB is outdated.

![image](https://user-images.githubusercontent.com/63544115/94371773-420df600-00f9-11eb-85ee-6e315bd6a640.png)

**Comment by bjornoleh** [comment] 2020-09-27 17:43
It looks pretty much the same in the reports:

![image](https://user-images.githubusercontent.com/63544115/94371837-af218b80-00f9-11eb-87cb-851ca49bc5bd.png)

**Comment by bjornoleh** [comment] 2020-09-27 17:56
Reverting to 14.0.4 Master: IOB and Loop/FreeAPS data are again up to date

![image](https://user-images.githubusercontent.com/63544115/94372110-6bc81c80-00fb-11eb-8a44-f4a1ca12f29e.png)

**Comment by sulkaharo** [comment] 2020-09-27 18:07
That's very curious. Is there anything in Nightscout logs that acts as a hint on what's going on? None of the changes in the update are Loop specific, all unit tests work and I'm seeing data updates to all collections going through as expected.

**Comment by bjornoleh** [comment] 2020-09-27 18:44
Which logs should I look at?

søn. 27. sep. 2020, 20:07 skrev Sulka Haro <notifications@github.com>:

**Comment by sulkaharo** [comment] 2020-09-27 18:48
The one Nightscout outputs - if you're on Heroku, check Papertrail

**Comment by bjornoleh** [comment] 2020-09-27 19:08
There are no new entries in devicestatur collection (mLab).

Yes, I'm on Heroku. In Papertrail there is this, some problem with the recent change with /pebble possibly? We have set up both NS instances DEVICESTATUS: denied, could there be some issue with the tokens?

Sep 27 12:02:16 xxxx app/web.1 **DENIED**:   158.xxx.xxx.63 no-token api:pebble,entries:read
Sep 27 12:02:17 xxxx heroku/router at=info method=GET path="/pebble?count=47" host=xxxx.herokuapp.com request_id=ca56d7a6-0ec3-4480-a579-a13612256237 fwd="158.xxx.xx.63" dyno=web.1 connect=1ms service=7ms status=401 bytes=758 protocol=https
Sep 27 12:02:17 xxxx app/web.1 **DENIED**:   158.xxx.xx.63 no-token api:pebble,entries:read
Sep 27 12:02:17 xxx heroku/router at=info method=GET path="/api/v2/properties" host=xxxx.herokuapp.com request_id=dfd889a8-649f-4f25-a722-7aaec15ce583 fwd="158.xxx.xx.63" dyno=web.1 connect=1ms service=59ms status=200 bytes=2730 protocol=https

**Comment by sulkaharo** [comment] 2020-09-27 19:13
The /pebble change only changed how the endpoint gets the configured units and did not affect the api permissions. That log at least shows you have some app trying to read the api but it's being denied. If this is Loop, it'll surely cause issues.

**Comment by bjornoleh** [comment] 2020-09-27 19:15
Apparently it does.

The treatments collection is updated as it should.

I  tried changing AUTH_DEFAULT_ROLES to readable, but no difference to be seen.

**Comment by bjornoleh** [comment] 2020-09-27 19:29
@sulkaharo Let me know if I can provide any other info or do some tests before I roll back to a working version for the night.

**Comment by sulkaharo** [comment] 2020-09-27 19:53
Can you try just removing AUTH_DEFAULT_ROLES for a sec to see if this is a permission issue?

**Comment by sulkaharo** [comment] 2020-09-27 19:59
Ok wait a second - how did you get that device status record? The _id record on it doesn't look right and trying to insert that would fail

**Comment by bjornoleh** [comment] 2020-09-27 20:04
@sulkaharo  Do you mean this bit?

"_id": {
    "$oid": "5f70dc5d1319bc000436874c"

It is just copied from mLab

**Comment by bjornoleh** [comment] 2020-09-27 20:20
Removing AUTH_DEFAULT_ROLES do not seem to make a difference in NS or mLab, but I don't think I see the error message in Papertrail any more...

**Comment by andrew-dixon** [comment] 2020-09-27 20:31
Having the same issue here, just going back to 14.0.2 to see if that fixes it, as that was the version I was on before I updated earlier today.

**Comment by andrew-dixon** [comment] 2020-09-27 20:37
@sulkaharo I've downgraded 14.0.2 and it is working again.

**Comment by sulkaharo** [comment] 2020-09-27 20:45
Did you see any errors in the Nightscout log? Looks like some some subtle little change happened that affects only Loop and this is practically impossible for me to debug. Ping @ps2

**Comment by bjornoleh** [comment] 2020-09-27 21:00
Not sure if his is any help?

WS: Connecion
WS: Disconnected


![image](https://user-images.githubusercontent.com/63544115/94375567-dd609480-0114-11eb-8b64-13330e0d5691.png)

![image](https://user-images.githubusercontent.com/63544115/94375605-24e72080-0115-11eb-8cba-ada0a513b70f.png)

**Comment by bjornoleh** [comment] 2020-09-27 21:01
I'll roll back to something that is working now, but let me know if I can test anything tomorrow.

**Comment by sulkaharo** [comment] 2020-09-28 05:39
Right, so if someone can PM me your instance URL in Discord, I can try to take a peek at the data to see if I can find a lead to what's the cause.

**Comment by sulkaharo** [comment] 2020-09-28 05:41
@bjornoleh the WS lines are about websocket connections, ie the Nightscout web app connecting to the backend. Loop uses the REST API, so the interesting lines would be either error stack traces or related to an app accessing /api/v1 URLs

**Comment by miki3421** [comment] 2020-09-28 06:31
Same for me. Following..

**Comment by sulkaharo** [comment] 2020-09-28 06:33
The above linked PR should fix this. @bjornoleh is testing the fix

**Comment by sulkaharo** [comment] 2020-09-28 06:37
(Looks like the reason this wasn't found in testing is, Loop does batch uploads _if_ the uploads have fallen behind. This only happens in situations like updating a production site. AFAIK testing is usually done by updating a site and pointing Loop to the updated site, which causes no downtime to be observed by Loop.)

**Comment by sulkaharo** [comment] 2020-09-28 10:11
This is now fixed in master as part of 14.0.6, please update your site to get the fix

**Closed by sulkaharo** 2020-09-28 10:11 UTC
