### ISSUE TITLE
Events in 24hr format are not shown in graph

### ISSUE THREAD

**Issue by anderfo** [nightscout/cgm-remote-monitor#449] opened 2015-03-01 11:04 UTC
Hey,
I'm using the 24-hour time format.
If I enter an insulin bolus, calibration/meter BG or other even before noon, it is indicated in the graph. However, afternoon events are not indicated.
In the "treatment list" they are listed in 12hr format eventhough they were entered using 24hr time, so I suppose it's just the plotting function which doesn't handle them properly.

cheers
  Anders

**Comment by jasoncalabrese** [comment] 2015-03-01 21:54
Duplicate of #407

**Closed** 2015-03-01 21:55 UTC
Labels: duplicate
