### ISSUE TITLE
Profile Report not working after updating to Mongo Atlas

### ISSUE THREAD

**Issue by tcanning** [nightscout/cgm-remote-monitor#5801] opened 2020-08-12 18:11 UTC
After updating to Mongo Atlas, when loading https://_____.herokuapp.com/report and running the Profiles report, the following fields are blank:
Insulin to carb ratio (I:C):
Insulin Sensitivity Factor (ISF):
Basal rates [unit/hour]:

I checked with two other users who had upgraded and displayed the same bug. I also tried different branches, all branches displayed the bug.

**Comment by jonfawcett** [comment] 2020-08-13 15:43
I can confirm that something is wrong with profiles after upgrading also. All reports appear to hang at 'Loading Profiles' and the Profiles screen errors out.

**Comment by jonfawcett** [comment] 2020-08-13 16:09
Heroku log trying to manually access the profile api shows a time out:
2020-08-13T16:01:16.524957+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/v1/profile.json?count=10" host=XXXXX.herokuapp.com request_id=8b5f98c0-6212-4869-acfb-650512838567 fwd="###.###.###.###" dyno=web.1 connect=1ms service=30003ms status=503 bytes=0 protocol=https

**Comment by unsoluble** [comment] 2020-08-13 23:24
Just as another data point, I can't seem to replicate this here. Master branch, Atlas DB, all Profile reports are full of appropriate data as expected.

**Comment by jonfawcett** [comment] 2020-08-14 00:43
@unsoluble My daughter is a Loop user and it stores probably 5-10x the volume of data than the NS profile editor in each record due to extra stuff like overrides. It also was uploading a new profile when not actually needed for NS functionality such as when changing dose strategy from Temp Basal to Auto Bolus or turning on an override. So I was seeing 1000-2000 profile uploads per month. I just purge the collection except 1 per day since July 1 and it solved the timeout.  So I'm not sure if it was a 'bad' entry or if it was a quantity of data issue causing the timeout.

**Comment by unsoluble** [comment] 2020-08-14 01:24
Hmm. We're also looping here. I do keep on top of nuking the devicestatus collection every week or so, but not sure if that's at all related.

**Comment by jonfawcett** [comment] 2020-08-14 01:52
I think it’s entirely the profile collection.  I’m running a customized AB branch that I added automatic switching (TB to AB based on BG reading) so that plus overrides created a lot of new profiles. Could be the volume or it could be that so many extra uploads just had a higher chance for an errant entry. Either way it seems NS may need either error checking on the call or a way to do it more efficiently? I looked at the code but don’t know it well enough to track down where to start.

So I made a change to Loop today to make it only upload profiles on basal, cr, and ISF changes to see if this keeps the issue resolved. You can apply the patch below if you want to try it. This also requires cleaning out the profiles collection if you get the timeout.

https://github.com/jonfawcett/Loop/commit/06b8a116eb475401c138042fee84ef600800f658.patch

**Comment by bjornoleh** [comment] 2020-08-14 21:37
Hi, I have not yet migrated out NS sites, but I am also not seeing the IC, ISF or basal in the Profiles report. So this may not be (entirely) a migration issue after all?

NS Dev 13.1.0, built from Dev as of a few weeks back or so.

**Comment by bjornoleh** [comment] 2020-08-16 20:36
I see the same lack of profile data in the most recent Dev.

**Comment by checkatillo** [comment] 2020-08-18 18:52
We saw some correlation with the region of Atlas cluster (like in Europe it defaults to Ireland and that one is a  lot more faulty than the one created in Frankfurt). But I saw people complaining about that even on Frankfurt clusters

**Comment by jonfawcett** [comment] 2020-08-18 19:05
I’m on AWS / N. Virginia (us-east-1)

**Comment by sulkaharo** [comment] 2020-08-18 19:26
Can someone affected load a profile object directly from the database and double check the data is actually intact.

**Comment by tcanning** [comment] 2020-08-18 19:46
Sulka, yes, the profile appears intact: https://nightscout-tuner.herokuapp.com/api/v1/profile.json

**Comment by Muppet1313** [comment] 2020-08-18 20:24
Here i can’t load the profile.
https://mosterd.herokuapp.com/api/v1/profile.json

**Comment by sulkaharo** [comment] 2020-08-19 04:16
Are you all either on latest release of Nightscout or dev made after release? Older releases have older Mongo drivers that might not be compatible with Atlas.

**Comment by sulkaharo** [comment] 2020-08-19 04:19
@Muppet1313 the profile does load but it's _huge_. As in big enough that I'm surprised how anything works with this. What's your looping setup, is this from AAPS?

**Comment by Muppet1313** [comment] 2020-08-19 06:20
I've been using FreeAPS since December. I will clean up the database first then. I use a lot of remote overrides and adjust the settings quite often.

**Comment by sulkaharo** [comment] 2020-08-19 06:53
@Muppet1313 Yes please try that. Right now the API returns 33 MB of JSON for the profiles. I'm surprised your Nightscout instance works at all.

**Comment by sulkaharo** [comment] 2020-08-19 08:04
The profile report issue should now be fixed in latest dev (359e6a6128e41b80371ba6bb67dec52b0058841d).

**Closed** 2020-08-19 08:05 UTC

**Comment by bjornoleh** [comment] 2020-08-26 19:24
Hi, sorry about poking a closed issue report, but. I think maybe the solution in that commit is a little crude? No offence, and thanks for getting things working!

This commit limits NS to load the last ten profiles. With the way Loop is writing to profiles at every temporary override, ten profiles gets you hardly a couple of days worth of previous settings.

https://github.com/nightscout/cgm-remote-monitor/commit/359e6a6128e41b80371ba6bb67dec52b0058841d

  "PROFILES_DEFAULT_COUNT" : 10, 

I did a quick teste with default count 100 and 500 instead, and both seems fine. It works for the profiles view, but not for reports, some other change seems needed there?

Of course, the bigger issue is the misuse of profiles by Loop, but that is addressed elsewhere.

**Comment by sulkaharo** [comment] 2020-08-26 19:59
The API to load a desired amount of profiles is at /api/v1/profiles.json?count=n and any system needing more than 10 profiles, which is what the Nightscout profile system is implemented for, can use that REST call. The basic problem here is, Loop is abusing the relatively open API Nightscout provides and stores _way_ more profile data than what the system is intended for, which is causing a variety of issues. Right now I have 0 active contributors looking at the codebase other than myself and as such have relatively little interest in spending time implementing workarounds that are specific to Loop, unless the Loop team or someone else commits to contributing whatever hours it takes to get a real fix in, including code changes for Loop.

**Comment by bjornoleh** [comment] 2020-08-26 20:14
Thanks, I perfectly understand your situation, and agree about the bigger issue. I found a workaround for my own need, to be able to at least see some previous profiles in NS.

Unfortunately, I can't offer much help beyond reporting what I find during normal use, and testing fixes and improvements that are made available. I hope someone competent in coding will give you a hand soon!

**Comment by jonfawcett** [comment] 2020-08-26 20:23
@sulkaharo 👍 I absolutely agree. I also saw that count= did not work on profiles in the api due to the volume of profile uploads from Loop. 

Going to drop a few notes here to hopefully help any Loop users that see this in the future. You should consider applying my Loop patch above. This limits Loop to only upload the profile when basal, ratio, or isf is changed. 

You’ll also want to clean out your historical profiles that Loop cluttered up the DB with or you may continue having issues. The simplest approach if you don’t know how to use mongo shell is to grab a trial of studio3t.

**Comment by bjornoleh** [comment] 2020-08-26 21:19
@jonfawcett I might try your patch. Would you be able to give a hint or two about how this should be applied? Can I easily use this for a workspace build (FreeAPS)? I see there are not too many changes, in only two files, so I suppose I will find a way, but probably not an easy one.

https://github.com/jonfawcett/Loop/commit/06b8a116eb475401c138042fee84ef600800f658

https://github.com/jonfawcett/Loop/commit/06b8a116eb475401c138042fee84ef600800f658.patch

Thanks!

**Comment by jonfawcett** [comment] 2020-08-26 22:41
@bjornoleh download the file to your Loop subfolder under your freeaps workspace download. Open terminal in that folder and run: git apply [patch filename]

**Comment by bjornoleh** [comment] 2020-08-27 18:35
@jonfawcett  Thanks a lot! That was easy!

I did get a warning about whitespaces, but it did not seem to matter? At least I could find the code changes in my files afterwards.

I built successfully to a simulator, so I suppose it will work.

Any known adverse effects from this patch?

Thanks again!

**Comment by jonfawcett** [comment] 2020-08-27 18:55
@bjornoleh I've not had any adverse effects in 2 weeks from it. You just need to remember to manually force change one of those 3 main profile items if you need to get a profile uploaded for other times. With Loop this really would only be when add/edit/delete an override so that it populates that list again for the care portal plugin

**Comment by bjornoleh** [comment] 2020-08-27 19:03
@jonfawcett  Aha, so I have to do a manual edit to get new/edited overrides to work from NS? Good to know (but will probably forget when needed).

I will give it a try.

**Comment by hummelstrand** [comment] 2020-08-28 10:29
I can report success in deleting old Loop entries in the "profile" table in Atlas-hosted mongoDB by using the free trial of Studio 3T and connecting to Atlas by copying the MONGO_CONNECTION string from Heroku and pasting that into the Studio 3T -> New Connection... -> From URI...

Tip: Type "1000" into the "Number of documents to show per page" and Shift-selecting the first and the last entry will let you delete 1,000 entries at a time.

**Comment by bjornoleh** [comment] 2020-08-28 10:40
Good to know. I have not migrated yet, so might wait until migration before cleaning profiles, the NS site is still working, but I guess that won't last forever.

@jonfawcett Did you document somewhere how to delete profiles while still keeping one per day? I totally understand if that is too much to ask, as I have no idea about how complicated that might be.

Is it easier to do a selective cleanup in Atlas or mLab?

**Comment by jonfawcett** [comment] 2020-08-28 10:57
Use studio3t and select all except 1 per day when deleting

**Comment by bjornoleh** [comment] 2020-08-28 14:13
Thanks, that did it. And thank you @hummelstrand for the tip about the MONGO_CONNECTION string from Heroku, I struggled a bit before noticing your post.

It's a bit of a chore deleting all-but one for each date manually, but that is what I ended up doing. Someone who knows SQL or similar would probably sift through the data a little faster...

**Comment by bjornoleh** [comment] 2020-09-04 07:20
I wrote a little while ago:
> This commit limits NS to load the last ten profiles. With the way Loop is writing to profiles at every temporary override, ten profiles gets you hardly a couple of days worth of previous settings.
> 
> [359e6a6](https://github.com/nightscout/cgm-remote-monitor/commit/359e6a6128e41b80371ba6bb67dec52b0058841d)
> 
> "PROFILES_DEFAULT_COUNT" : 10,
> 
> I did a quick test with default count 100 and 500 instead, and both seems fine. It works for the profiles view, but not for reports, some other change seems needed there?

Now that I have reduced my "profile" collection in mLab to around 100 entries, and running the latest NS Dev (as of yesterday) without modifications, the "Profiles report" works fine, and I can load the profiles from several months back. The "Profile editor" show only the last ten entries, but that is fine as long as I can find the rest in the report. 

I also applied the patch mentioned above to Loop (FreeAPS, workspace). This works as expected, and I am glad i did this. The only thing to be aware of, as mentioned above: To get new or edited overrides to work from NS, you have to do a manual edit of one of the profile parameters in Loop. This will write a new profile entry in the NS database, which also includes any changes to the preset overrides.

**Comment by sulkaharo** [comment] 2020-09-23 11:10
Note to here as well: I added the count parameter support to the /profile REST call and bumped the number of profiles loaded for the reports and profile editor so these should now with the release. Sadly this doesn't fix the issue that the API doesn't return semantically sensible data under Loop, where most profiles are the same for the insulin dosing and the amount of data in the profile collection is huge for Loop users, so if you're accessing the API to load the data, assume you'll need to process a lot of profiles
