### ISSUE TITLE
Clock view ignores Time format

### ISSUE THREAD

**Issue by herzogmedia** [nightscout/cgm-remote-monitor#3832] opened 2018-08-12 16:24 UTC
The Clock view (bgclock.html) does not show the current time in the 24 hour date format, even when it is selected in the preferences.

Is this a new bug with the latest release, have you seen this earlier?
was also there in 0.10.2

Which device / browser version was used to reproduce the bug?
Firefox 61.0.2 on Win10

Does this happen every time you launch Nightscout, or sometimes?
happens always ;)

... I can try to fix it myself but don't know if and when I'll find the time.

**Comment by unsoluble** [comment] 2018-10-16 22:32
I'm digging into this one. The issue is clear — `window.serverSettings.settings.timeFormat` is pulling straight from the config variable defaults instead of from wherever the time setting is stored in the active profile — but I haven't been able to figure out the data path yet. If someone can point me in the right direction, could fix this one.

**Comment by sulkaharo** [comment] 2019-05-19 10:27
@unsoluble by "active profile", do you mean the local client settings that can override the server setting?

**Comment by sulkaharo** [comment] 2019-05-19 10:42
Looks like the client isn't doing a full init on the clock faces, so not all variables are available, need to look at that later

**Comment by unsoluble** [comment] 2019-05-19 18:41
@herzogmedia We'll be able to fix the time thing now — will incorporate into #4639.

**Comment by unsoluble** [comment] 2019-05-19 20:38
Fixed in #4641

**Closed** 2021-02-14 10:11 UTC
Labels: closed-due-inactivity
