### ISSUE TITLE
SGV missing in clock views

### ISSUE THREAD

**Issue by ireneusz-ptak** [nightscout/cgm-remote-monitor#6629] opened 2020-12-08 18:40 UTC
It seems after last changes in clock views the SGV is missing for some users - apparently not every source returns sgv.scaled field in V2 API:

sgvs: [{_id: "5fcfc3919b809f49a4e7484f", mgdl: 176, mills: 1607451523000, device: "share2",…}]
0: {_id: "5fcfc3919b809f49a4e7484f", mgdl: 176, mills: 1607451523000, device: "share2",…}
device: "share2"
direction: "FortyFiveDown"
mgdl: 176
mills: 1607451523000
type: "sgv"
_id: "5fcfc3919b809f49a4e7484f"

**To Reproduce**
/api/v2/properties call returning no sgv.scaled value which is currently the source for SGV

**Expected behavior**
SGV present in the clock view :)

**Your setup information**
NS 14.0.7
CGM source - Loop, I think

**Additional context**
I have no time to pick that up right now, but maybe someone is willing to fix it (/lib/client/clock-client.js or in api itself?)

**Comment by woodduckie** [comment] 2020-12-08 20:18
Thanks @ireneusz-ptak!  The issue is with my site.

CGM source is Dexcom Share bridge with G6.  I have in the past used xdrip & spike (if relevant).

I currently push data from Loop (no CGM data though), and have used OpenAPS in the past as well.

**Comment by sulkaharo** [comment] 2020-12-08 20:21
This should be fixed in dev

**Comment by woodduckie** [comment] 2020-12-08 21:12
Thank you Sulka!  I brought the recent changes on clock-client.js & bgnow.js over & all is well.

**Closed** 2021-02-02 18:19 UTC

**Comment by HenrikAntin** [comment] 2021-06-20 12:42
Hi! Could you please advise on how to fix this? Source files and what to change? Km running Nightscout 14.0.7 in Azure.
Have tied to upgrade but just gives me errors
Best regards
Henrik
