### ISSUE TITLE
Treatment edit/delete failures

### ISSUE THREAD

**Issue by mpangburn** [nightscout/cgm-remote-monitor#3603] opened 2018-05-26 22:33 UTC
Both the reports GUI and the API are very unreliable with respect to treatment edits and deletions.
When going to Reports -> Treatments and using the green pencil to edit or the red x to delete, there is no indication of success, and confirming an edit or delete appears to have no effect.

Similarly, when invoking the API with PUT/DELETE requests, the outcomes are unpredictable. Sometimes an update succeeds normally, but more often it produces an additional treatment with the same ID without deleting the prior. Deletions appear to fail consistently. These calls to the API return successful HTTP responses but do not achieve the desired effect.

Nightscout v0.10.2

**Comment by PieterGit** [comment] 2018-06-27 18:58
Do the problems occur with all major browsers (Chrome, Firefox, Safari). Do you see errosr in the Javascript console somehow.

**Comment by razor459** [comment] 2018-08-11 13:56
v0.10.3 in Safari on MacOS
It appears the issue is that it does not display the updated data. Clearing the cache and refreshing the page shows that the edit succeeded.

Problem also exist when editing Treatments via Report in Nightscout and NIghtscout X iOS apps

**Comment by PieterGit** [comment] 2018-10-24 16:05
@razor459 @mpangburn This has been fixed with https://github.com/nightscout/cgm-remote-monitor/pull/3957 . Please confirm that this works for you. Closing this issue. Feel free to reopen it if the problem persist. You need to install latest `dev` branch sinds 0.11 has not been released yet.

**Closed by PieterGit** 2018-10-24 16:05 UTC
Labels: bug, help wanted
