### ISSUE TITLE
When profile is in mg/dL and you set your site to mmol (and vice versa) all calculations are off

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#1356] opened 2015-11-16 12:59 UTC
##

**Comment by sulkaharo** [comment] 2016-04-24 08:32
Should we change the profile object API so that the calls to access the data have to specify the units & translate the units on the fly?

**Comment by oskarpearson** [comment] 2016-12-21 19:20
This looks like a duplicate of https://github.com/nightscout/cgm-remote-monitor/issues/367 - I'm closing it unless there are objections. Please re-open if necessary.

**Closed by oskarpearson** 2016-12-21 19:20 UTC
