### ISSUE TITLE
Azure QuotaExceeded with latest update

### ISSUE THREAD

**Issue by kimnjeru** [nightscout/cgm-remote-monitor#2906] opened 2017-10-09 21:26 UTC
My Azure websites has been stopped due to exceeding the quota allocated to the Pay As you Go subscription.  I have the free tier. 
Is anyone else experiencing this?  I updated to the most recent update yesterday.
Help!

**Comment by sulkaharo** [comment] 2017-10-14 11:43
Was this during deployment or just hosting? I recommend you transfer the hosting of your site to Heroku.com; their setup is significantly simpler than Azure and their free tier has much more capacity than on Azure. See the Deploy to Heroku button on our GitHub front page, then just copy the settings from Azure and it should work (no need to re-deploy mLab) https://github.com/nightscout/cgm-remote-monitor

**Comment by PieterGit** [comment] 2017-11-11 11:20
@kimnjeru can you give an update on this issue?

**Comment by kimnjeru** [comment] 2017-11-11 17:26
Hi. I switched to Heroku and no more problems so far.

**Comment by oschumac** [comment] 2017-11-19 13:31
Hi, i switched to heroku too, but now i got the message that i need to upgrade. Cause i have used 80% of 1000 hour free dyno hours. Since 3 years i use Nightscout and i never had to have upgrade to a paid account. Has someone a solution for that ?

**Comment by alfiearthur** [comment] 2017-12-25 20:48
We have just had a failure to deploy on Azure with exactly the same message as  oschumak above. It also says; Merge brance 'dev' GitHub Failed. 
Any advice welcomed.

**Comment by abcooke0** [comment] 2017-12-26 00:13
Having the same issue failing to deploy:

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Using start-up script server.js from package.json.
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3.
Selected node.js version 8.9.3. Use package.json file to choose a different version.
Selected npm version 5.3.0
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN invalid config scripts-prepend-node-path="--production"
npm ERR! path D:\home\site\wwwroot\node_modules\fsevents\node_modules\getpass\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2017-12-26T00_07_41_562Z-debug.log
An error has occurred during web site deployment.
npm failed
npm WARN invalid config scripts-prepend-node-path="--production"\r\nnpm ERR! path D:\home\site\wwwroot\node_modules\fsevents\node_modules\getpass\node_modules\r\nnpm ERR! code EPERM\r\nnpm ERR! errno -4048\r\nnpm ERR! syscall scandir\r\nnpm ERR! Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\getpass\node_modules'\r\nnpm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\getpass\node_modules'\r\nnpm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',\r\nnpm ERR!   errno: -4048,\r\nnpm ERR!   code: 'EPERM',\r\nnpm ERR!   syscall: 'scandir',\r\nnpm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }\r\nnpm ERR! \r\nnpm ERR! Please try running this command again as root/Administrator.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     D:\local\AppData\npm-cache\_logs\2017-12-26T00_07_41_562Z-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\69.61204.3166\bin\Scripts\starter.cmd bash deploy.sh

**Comment by alfiearthur** [comment] 2017-12-26 01:17
I've just set the whole system up on Heroku and it worked first time. Can't use my existing Azure account, though, sadly. We have T1D 13 year old. We're using Freestyle Libre with Blucon and a 3d printed holder from thingiverse. We were bluetoothing through the bedroom wall, but we're now using nightscout for the first time. Great Christmas present. Thanks to all developers that made this happen.

**Comment by Woobagcgm** [comment] 2018-01-09 11:00
Same problem here after i've updated my cgm-remote-monitor to Azure, using the Nightscout update function 
(http://www.nightscout.info/wiki/welcome/how-to-update-to-latest-cgm-remote-monitor-aka-cookie)

I've deleted the node line in package.json. I've found this in an old issue. But didn't work for me.
(https://github.com/nightscout/cgm-remote-monitor/issues/1412)

My log:

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Using start-up script server.js from package.json.
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 0.10.40.
Selected npm version 1.4.28
npm WARN package.json estraverse@4.2.0 No README data
npm WARN package.json jquery-ui-bundle@1.12.1 No README data
npm WARN package.json setimmediate@1.0.5 No README data
npm WARN package.json tr46@0.0.3 No README data
npm WARN package.json whatwg-encoding@1.0.1 No README data
npm WARN package.json assert@1.4.1 assert is also the name of a node core module.
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json buffer@4.9.1 buffer is also the name of a node core module.
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN package.json events@1.1.1 events is also the name of a node core module.
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json flot@0.8.0-alpha No repository field.
npm WARN package.json has-binary@0.1.7 No repository field.
npm WARN package.json indexof@0.0.1 No repository field.
npm WARN package.json jquery.tipsy@1.0.3 script should probably be scripts.
npm WARN package.json object-component@0.0.3 No repository field.
npm WARN package.json path@0.12.7 path is also the name of a node core module.
npm WARN package.json punycode@1.4.1 punycode is also the name of a node core module.
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
npm WARN package.json string_decoder@1.0.3 string_decoder is also the name of a node core module.
npm WARN package.json util@0.10.3 util is also the name of a node core module.
npm WARN package.json url@0.11.0 url is also the name of a node core module.
npm ERR! Error: Invalid Package: expected types/node but found @types/node
npm ERR!     at D:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-local-tarball.js:161:14
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
An error has occurred during web site deployment.
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm failed

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--scripts-prepend-node-path" "--production"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm
npm WARN package.json estraverse@4.2.0 No README data\r\nnpm WARN package.json jquery-ui-bundle@1.12.1 No README data\r\nnpm WARN package.json setimmediate@1.0.5 No README data\r\nnpm WARN package.json tr46@0.0.3 No README data\r\nnpm WARN package.json whatwg-encoding@1.0.1 No README data\r\nnpm WARN package.json assert@1.4.1 assert is also the name of a node core module.\r\nnpm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.\r\nnpm WARN package.json buffer@4.9.1 buffer is also the name of a node core module.\r\nnpm WARN package.json callsite@1.0.0 No repository field.\r\nnpm WARN package.json events@1.1.1 events is also the name of a node core module.\r\nnpm WARN package.json eyes@0.1.8 No repository field.\r\nnpm WARN package.json flot@0.8.0-alpha No repository field.\r\nnpm WARN package.json has-binary@0.1.7 No repository field.\r\nnpm WARN package.json indexof@0.0.1 No repository field.\r\nnpm WARN package.json jquery.tipsy@1.0.3 script should probably be scripts.\r\nnpm WARN package.json object-component@0.0.3 No repository field.\r\nnpm WARN package.json path@0.12.7 path is also the name of a node core module.\r\nnpm WARN package.json punycode@1.4.1 punycode is also the name of a node core module.\r\nnpm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.\r\nnpm WARN package.json string_decoder@1.0.3 string_decoder is also the name of a node core module.\r\nnpm WARN package.json util@0.10.3 util is also the name of a node core module.\r\nnpm WARN package.json url@0.11.0 url is also the name of a node core module.\r\nnpm ERR! Error: Invalid Package: expected types/node but found @types/node\r\nnpm ERR!     at D:\Program Files (x86)\npm\1.4.28\node_modules\npm\lib\cache\add-local-tarball.js:161:14\r\nnpm ERR!     at process._tickCallback (node.js:448:13)\r\nnpm ERR! If you need help, you may report this *entire* log,\r\nnpm ERR! including the npm and node versions, at:\r\nnpm ERR!     <http://github.com/npm/npm/issues>\r\n\r\nnpm ERR! System Windows_NT 6.2.9200\r\nnpm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--scripts-prepend-node-path" "--production"\r\nnpm ERR! cwd D:\home\site\wwwroot\r\nnpm ERR! node -v v0.10.40\r\nnpm ERR! npm -v 1.4.28\r\nnpm\r\nD:\Program Files (x86)\SiteExtensions\Kudu\70.10102.3204\bin\Scripts\starter.cmd bash deploy.sh

**Comment by sulkaharo** [comment] 2018-01-09 11:09
The Azure deploy fail cause is unknown. People have been able to fix it by just retrying again; some users have fixed it by first disconnecting their Github account from Azure and then re-connecting & deploying. FWIW I'm personally hosting NS in Heroku and never see these issues.

**Comment by Kdisimone** [comment] 2018-02-21 19:45
This issue looks like it can be closed.  If anyone has a lingering issue with their deployment, please chime in?

**Comment by PieterGit** [comment] 2018-02-26 19:20
Closing issue. Feel free to reopen or create a new issue if there is more information and the problem is persisting.

**Closed by PieterGit** 2018-02-26 19:20 UTC
Labels: hosting-azure
