### ISSUE TITLE
No button text visible on API secret entry screen (Device authentication) on mobile browsers

### ISSUE THREAD

**Issue by wootmasterslick** [nightscout/cgm-remote-monitor#4258] opened 2019-02-04 09:46 UTC
**Describe the bug**
See title

**To Reproduce**
1. Go to nightscout profile page
2. Click on authenticate device
3. Enter API secret
4. See that the acknowledge area has no inage to define the OK action

**Expected behavior**
Image at the position indicating where to click to acknowlegde API secret entry.

**Screenshots**
https://imgur.com/gallery/otZrcVq

**Your setup information**
- What version of Nightscout 

0.11.0-dev-20181231 | 46b7e67f364bcaad9fc5f5743c8079eebbea9026
-- | --

- Is your issue specific to a browser (experienced at least on Firefox and Iphone)

**Comment by unsoluble** [comment] 2019-02-05 20:07
Can confirm this in MobileSafar on 0.10.3 as well. Not sure where the code for this UI is.

**Comment by PieterGit** [comment] 2019-02-05 21:49
@wootmasterslick @unsoluble 
I assume you mean the `Update` text in the button in the lower right is missing. That's not an image, but text. I can't reproduce this with Chrome and `0.11.0-rc1-20190205`. Can you try:
- try to select the text in the button. Eg. I can select the button text: 
![image](https://user-images.githubusercontent.com/6500826/52306462-52a7b080-2998-11e9-9acf-1f83193e3514.png)
- can you use the browser inspect function to see the HTML code and the CSS code that's active. I now Firefox can do that. E.g. in my case it shows the css on `<button type="button" class="ui-button ui-corner-all ui-widget">Update</button>`
- can you try to reproduce it in the `dev` branch (currently `0.11.0-rc1-20190205`) .

**Comment by unsoluble** [comment] 2019-02-05 22:11
It's text, yes, but it's rendering as black-on-black in mobile browsers. Do you know which file this interface window is located in?

**Comment by PieterGit** [comment] 2019-02-06 06:33
Workaround is to set the mobile browser into "Desktop site" mode, but I agree we need to redesign this popup for mobile. 

The Device authentication popup window also too wide with Chrome on Samsung S7, but the button text "Update" is shown with that mobile browser.

Please PR against the `dev` branch. The code can be found here
https://github.com/nightscout/cgm-remote-monitor/blob/52e1ff054c98a6c0ee90d6f3b4d5c299e2b6dd40/lib/hashauth.js#L170-L183
(master version).

Setting fix for version to Nightscout 0.12 .

**Comment by sulkaharo** [comment] 2019-02-07 11:19
#4270 fixes this for the button on iOS. @PieterGit says the UI also fails on Android Chrome, but in different ways. Can someone test on Android and post pictures?

**Comment by PieterGit** [comment] 2019-02-21 08:13
Closing issue. Is fixed in 0.11.1 with fix of @sulkaharo .

**Closed by PieterGit** 2019-02-21 08:13 UTC
