### ISSUE TITLE
Nightscout does not show a Trend arrow

### ISSUE THREAD

**Issue by Flori3000** [nightscout/cgm-remote-monitor#7201] opened 2021-12-01 10:26 UTC
**Subject of the issue**
Nightscout does not show a trend arrow anymore.
![image](https://user-images.githubusercontent.com/26416864/144216538-27756bac-cefc-4fb1-afb6-a9213e96f847.png)

**Your environment**
Nightscout version 14.2.4
Source for BG values:  Dexcom Share (EU)

**Expected behavior**
Show trend arrows

**Steps to reproduce the behavior:**
Set up Dexcom Share as source for BG values.

**Info:**
Found this  [here](https://github.com/NightscoutFoundation/xDrip/issues/1884#issuecomment-983315112).
"It looks like Dexcom changed the BG arrow trend indicator value (slope) from a number to a string."

**Comment by herzogmedia** [comment] 2021-12-01 11:07
does you Dexcom App still work as expected? I've got the same behaviour but for me the Dexcom App now thinks my smart device was not compatible

**Comment by Flori3000** [comment] 2021-12-01 11:40
Dexcom App on iOS and Dexcom Follow on an Android device are working as expexted.

**Comment by eggepegge** [comment] 2021-12-01 11:44
I've got the same behaviour. Nightscout 14.0.6, getting values from Dexcom Share (EU). The interesting thing is that in my dexcom Follow app (I'm only a follower) I get the trend arrow, and even more interesting, in xDrip having my nightscout as source, I also get the trend arrow. But in the Nightscout web gui it looks like in the screendump above, and via the API I get direction NONE. Ah, and there "trend" explain why I get the arrow in xDrip....

```
$ curl -q https://tuvisen.herokuapp.com/api/v1/entries/current.json |json_pp 
[
   {
      "sysTime" : "2021-12-01T11:36:56.000Z",
      "_id" : "xxx",
      "device" : "share2",
      "trend" : "DoubleUp",
      "date" : 1638358616000,
      "type" : "sgv",
      "dateString" : "2021-12-01T11:36:56.000Z",
      "direction" : "NONE",
      "sgv" : 280,
      "utcOffset" : 0
   }
]

```

**Comment by Flori3000** [comment] 2021-12-01 11:53
@eggepegge same behaviour for me.

**Comment by sulkaharo** [comment] 2021-12-01 12:04
How are you inserting data into Nightscout? The trend arrow uses the "direction" field value and if your data source is inserting NONE as the value for this field, no arrow will be shown.

**Comment by Flori3000** [comment] 2021-12-01 12:08
Seems to be related to this [issue](https://github.com/nightscout/share2nightscout-bridge/pull/51?fbclid=IwAR1gzEOkciYeleYdQ_0qpIp3UFPuR3WbM3g2oPpBh7JsI5amaPBPCy0nyyI#issue-1067646209)

**Comment by eggepegge** [comment] 2021-12-01 14:05
> How are you inserting data into Nightscout? The trend arrow uses the "direction" field value and if your data source is inserting NONE as the value for this field, no arrow will be shown.

I'm populating nightscout from Dexcom Share (EU). As Flori3000 mentioned, seem to be related to [this](https://github.com/nightscout/share2nightscout-bridge/pull/51).

**Comment by charlotte130210** [comment] 2021-12-01 22:40
I´ve got the same problem with the trend arrow as shown above.

Nightscout version 14.2.4
Source for BG values: Dexcom Share (EU)

The missing trend arrow appears without the stop being changed.

Is it required in the Heroku Config Vars to use a certain parameter for DIRECTION?

**Comment by tuim** [comment] 2021-12-03 17:54
Thanks for your work on this. When should we expect to see the fix on master?

**Comment by bewest** [comment] 2021-12-03 18:12
We've asked for help testing the changes in https://github.com/nightscout/cgm-remote-monitor/pull/7146.  Once testers for Medtronic Careportal and Dexcom Share can help us achieve high confidence that the changes work as intended, we will issue a new release.

https://www.facebook.com/groups/cgminthecloud/posts/4630775833710303/?comment_id=4636379419816611

Thanks to early feedback, we have continued to make changes to Nightscout's cloud-to-cloud synchronization capabilities.
For Dexcom Share folks we need the following circumstances tested:
* old-style usernames
* email-based usernames
* EU or OUS testers
* US testers
For Medtronic Carelink folks, we need the following scenarios tested:
* Carepartner account
* Patient account
* outside United States
* inside United States

**Comment by tuim** [comment] 2021-12-03 19:43
on it. Thank you!

**Comment by pdaddyo** [comment] 2021-12-03 20:32
I'm trying to test this fix (in EU) via the official `latest_dev` docker image (built 2 days ago) but I'm getting `Error: Cannot find module jsdom` during startup (just after connecting to mongo).  Switching back to `latest` image works fine except for the broken trend arrow, which by the way we suspect is also the culprit crashing my wife's garmin watchface for last day or so!  Thanks everyone for your help on this.

**Comment by ideaweb** [comment] 2021-12-08 14:44
I am not a developer and found a quick and dirty "fix". Maybe its wrong, catches not all cases or causes other side effects, but for me its urgent and it helps me to get it working until the team from Nightscout realeasing a new version with a better fix.

[./node_modules/share2nightscout-bridge/index.js](https://github.com/nightscout/share2nightscout-bridge/blob/master/index.js)

I added a new line in front of return statement to get arrows back.

```
function trendToDirection (trend) {
  typeof trend === 'number' || (trend = (DIRECTIONS[trend] || 0));
  return Trends[trend] || Trends[0];
}
```
On trouble or on any update please do not forget to revert it.

**Comment by pdaddyo** [comment] 2021-12-08 15:54
Latest dev build is working with arrows restored (we're on EU bridge), thanks all.

**Comment by JasmineT1D** [comment] 2021-12-09 22:36
I'm in the US and the arrows are still showing <=>. Is there a fix for US users yet?

**Comment by Domfunkle** [comment] 2021-12-09 22:40
The issue was with the nightscout/share2nightscout-bridge node module. The module was updated, but you need to update your package.json file to use the latest version 0.2.8 and then redeploy:  "share2nightscout-bridge": "^0.2.8"

**Comment by JasmineT1D** [comment] 2021-12-09 22:52
Thanks Domfunkle. I'm a total novice user though and have only done master version updates. Do you know when this fix will be available to update via the master update or is there any chance you can post instructions on how to update the module you noted?

**Comment by cpitchford** [comment] 2021-12-09 23:55
I have deployed the dev branch locally and I'm running without problem.

* I am using the share2nightscout-bridge 0.2.8
* I am a EU/UK User with non-email style Dexcom username
* I am running on Ubuntu 18.04/Nodejs 12(nodesource package)

**Comment by JasmineT1D** [comment] 2021-12-10 00:30
Thank you for the additional info cpitchford! I just deployed on the Dev branch and the arrow is indeed back! For anyone interested here is a link with detailed instructions on how to deploy the dev branch.

https://nightscout.github.io/update/dev_branch/?fbclid=IwAR2hKwg_2anGOzzQp4SBTrTn9l60IfHInUcLwIDtlRd9qMNU5cWVoLWVMQA

**Comment by herzogmedia** [comment] 2021-12-10 12:05
The [current master release 14.2.5](https://github.com/nightscout/cgm-remote-monitor/releases/tag/14.2.5) should fix it now. Thanks @bewest

**Comment by bewest** [comment] 2021-12-10 19:23
Closing for now.  The trend arrows should be restored.  In addition, there should be less lag fetching new glucose readings from Dexcom. https://github.com/nightscout/cgm-remote-monitor/releases/tag/14.2.5

**Closed by bewest** 2021-12-10 19:23 UTC
