### ISSUE TITLE
Miao miao not uploading and Glimp telling me incorrect API secret?

### ISSUE THREAD

**Issue by aliozoila** [nightscout/cgm-remote-monitor#5371] opened 2019-12-26 10:40 UTC
I have just got a Miao Miao which works perfectly with its tomato app. 
I have just created a website following the instructions on the nightscout app, via heroku and github. I entered the website and API secret in my tomato app it said "success". However when I try to add the website to the Glimp app it's telling the API secret is incorrect. I have made two websites this morning to be sure that I had done everything correctly and it's still telling me the API secret is incorrect and also my MiaoMiao data isn't uploading the nightscout website! Have I missed something? I've never done anything like this before, and not great at in depth technology like this webiste and app creating stuff. So simply explained troubleshooting ideas are welcome. Help! 

The main support channel is on Facebook: please join the CGM In The Cloud Facebook group (https://www.facebook.com/groups/cgminthecloud) and start a post there. 

**Suggestions to include in your post when you are asking for help:**
1. Include what you are trying to do: ("*I am trying to set up Nightscout for the first time.*")
2. Include which step you are on and what the problem is: ("*I deployed on Heroku, but I'm not seeing any BG data.*")
3. If possible, include a link to the version of documentation you are following ("*I'm following the OpenAPS Nightscout setup docs (https://openaps.readthedocs.io/en/latest/docs/While%20You%20Wait%20For%20Gear/nightscout-setup.html#nightscout-setup-with-heroku)*")

Other places you can find support and assistance for Nightscout include Gitter's [nightscout/public](https://gitter.im/nightscout/public) channel.

**Comment by OpossumGit** [comment] 2019-12-31 07:41
I believe this is a bug of Glimp. When I press Test connection button it also says API secret is not correct, but everything works fine anyway. Data gets uploaded. 

Maybe it is something in recent versions of Nightscout that confuses Glimp

**Comment by sulkaharo** [comment] 2020-01-01 09:44
Yup this sounds like you should get in touch with Glimp developers

**Comment by bolt911-bernie** [comment] 2020-01-01 13:13
I’ve noticed a bug in the implementation for tomato where the url for Nightscout has a capital H added to the front,  when setup on an iPhone 

Eg the url reads Https rather than https this breaks the upload to Nightscout for some reason  Have you checked that glimp isn’t susceptible to this and is parsing the url correctly.

**Comment by aclowkey** [comment] 2020-12-03 11:57
Any updaet on it?

**Comment by sulkaharo** [comment] 2020-12-03 12:57
Closing this, as the issue is not specific to Nightscout and no progress is likely reported here

**Closed by sulkaharo** 2020-12-03 12:57 UTC
