### ISSUE TITLE
Value not displayed when it is old

### ISSUE THREAD

**Issue by OpossumGit** [nightscout/cgm-remote-monitor#5313] opened 2019-12-17 22:43 UTC
When data is old, value is not rendered. - - - is displayed. That happens after roughly 10 minutes. 

It happens on v13.0, while old versions were always displaying latest value. 

1. Stop collection
2. Look at NS site after 15 minutes

I use Libre and it is not always with blucon/MiaoMiao but is scanned periodically which leads to delays. 

I look at Safari on iPhone. 

![7B191F65-7B3A-47BE-B5DD-1604C52134B5](https://user-images.githubusercontent.com/9529545/71040514-033d1f80-2127-11ea-9ae3-b2c471371c85.jpeg)

**Comment by OpossumGit** [comment] 2019-12-17 22:46
If it makes any difference, I scan with Glimp app.

**Comment by jpcunningh** [comment] 2019-12-17 22:48
@OpossumGit, I believe this is intended behavior.  There was a bug that was fixed in v13.0 to make it display the -- when the data age is greater than 15 minutes.

**Comment by OpossumGit** [comment] 2019-12-17 22:56
@jpcunningh maybe you can point me to lines of code where it was fixed, so I can make my own version. 

Or alternatively this can be made as option somewhere (number of minutes before hiding)? Or number of minutes might be tied to stale data warn so I can extend that warning trigger?

**Comment by jpcunningh** [comment] 2019-12-17 23:09
Here is the location where it's cleared and set to ---:
https://github.com/nightscout/cgm-remote-monitor/blob/41ac93f7217b1b7023ec6ad6fc35d29dcf2e4f88/lib/client/index.js#L579

**Comment by OpossumGit** [comment] 2019-12-17 23:16
👍thanks. I’ll make my own version per my requirement. 
Someone more senior can decide whether this issue is to be closed or it will be used as idea for future change (make this customizable)

**Comment by sulkaharo** [comment] 2020-01-01 09:53
Not displaying the BG value when it's stale is a safety feature, to ensure users do not assume the data is up to date when it's actually stale. Closing.

**Closed by sulkaharo** 2020-01-01 09:53 UTC
